name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  terraform-plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./infrastructure

    env:
      TF_VAR_user_ocid: ${{ secrets.OCI_USER_OCID }}
      TF_VAR_tenancy_ocid: ${{ secrets.OCI_TENANCY_OCID }}
      TF_VAR_fingerprint: ${{ secrets.OCI_FINGERPRINT }}
      TF_VAR_region: ${{ secrets.OCI_REGION }}
      TF_VAR_private_key_path: /home/runner/work/_temp/oci_api_key.pem

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Write Private Key
        run: |
          echo "${{ secrets.OCI_PRIVATE_KEY }}" > /home/runner/work/_temp/oci_api_key.pem
          chmod 600 /home/runner/work/_temp/oci_api_key.pem

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -input=false

  terraform-apply:
    name: 'Terraform Apply'
    needs: terraform-plan
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        working-directory: ./infrastructure

    env:
      TF_VAR_user_ocid: ${{ secrets.OCI_USER_OCID }}
      TF_VAR_tenancy_ocid: ${{ secrets.OCI_TENANCY_OCID }}
      TF_VAR_fingerprint: ${{ secrets.OCI_FINGERPRINT }}
      TF_VAR_region: ${{ secrets.OCI_REGION }}
      TF_VAR_private_key_path: /home/runner/work/_temp/oci_api_key.pem

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Write Private Key
        run: |
          echo "${{ secrets.OCI_PRIVATE_KEY }}" > /home/runner/work/_temp/oci_api_key.pem
          chmod 600 /home/runner/work/_temp/oci_api_key.pem

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
